### ISSUE TITLE
executing script tag with React - causes conflict with css

### ISSUE THREAD

**Issue by Dawa12** [Dawa12/final-project#2]
I am doing front end fetch calls to the Facebook API. I'm doing this within my React App.jsx, within it's componentDidMount() function. 

I'm writing quite a bit of code in that function, and I'm sure that there's a better way to do that. However, I noticed that this calling from the FB API and appending to the DOM affects me from customizing specific elements with css selectors. I can still customize the font color for all <p> tags but I cannot for a <p> tag with a specific classname or id.

I'm even considering just removing React from my application to find a workaround.

Overall I just wanted to discuss what changes I should consider to have my project ready for tomorrow. 

Three things I did to attempt to solve this issue:
- searched FB JS SDK documentation
- googled / youtubed tutorials
- console logged many places in my app, and isolated problem

Thanks!

[https://github.com/Dawa12/final-project/tree/components](https://github.com/Dawa12/final-project/tree/components)

@jasonseminara @rapala61 @gittheking @irwintsay @trevorpreston

**Comment by Dawa12** [comment]
@mgershowitz

**Comment by trevorpreston** [comment]
queued
